fastlane_version "2.30.2"

default_platform :mac

platform :mac do
  desc "Runs danger"
  lane :check_pull_request do
    danger
  end

  desc "Runs release build"
  lane :build do
    Dir.chdir("..") do
      sh "make build"
    end
  end

  desc "Runs all the tests"
  lane :test do
    Dir.chdir("..") do
      sh "make test"
    end
  end
end
