fastlane_version "2.96.1"

default_platform :mac

platform :mac do
  desc "Runs release build"
  lane :build do
    Dir.chdir("..") do
      sh "make build"
    end
  end

  desc "Runs all the tests"
  lane :test do
    Dir.chdir("..") do
      sh "make test"
    end
  end
end
